TOPDIR=../..
# This Makefile requires the definition of thes environment variables:
#
#    TOPDIR  The directory where Makefile.rules resides.
#            Usually this would be ${SCV_INSTALL}/examples.

SOURCE_FILES=test.cc

include ${TOPDIR}/Makefile.rules
